### PR TITLE
Update widgets.py

### PR DESCRIPTION
**Pull request by Hopiu**
How about adding those extra variables to the widgets context? This would give some extra flexibility in rendering the template. For example bootstrap tabs: 
```
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
   <li class="nav-item">
     <a class="nav-link active" data-toggle="tab" href="#edit-{{attrs.id}}" role="tab">Edit</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" data-toggle="tab" href="#preview-{{attrs.id}}" role="tab">Preview</a>
   </li>
</ul>
<!-- Tab panes -->
<div class="tab-content markdownx">
   <div class="tab-pane active" id="edit-{{attrs.id}}" role="tabpanel">
     {{ markdownx_editor }}
   </div>
   <div class="tab-pane" id="preview-{{attrs.id}}" role="tabpanel">
     <div class="markdownx-preview"></div>
   </div>
</div>
```

### CODE REVIEW

**Comment by xenatisch** [comment]
I have looked at this at least 10 times, and I just don't get it. Could you explain it to me like I'm an idiot? What advantages does it add, and how is it different to what we're doing right now?

We cannot use ID for distinguishing between different items. There may (a) be more than one editor / preview set in one page, and (b) we would have no way of knowing the IDs in our JavaScript code, unless it is hardcoded by the user, which would introduce an additional level of complexity. Plus, we already have a way of setting attributes, so why do you think we need to embed them into our `render` method, which btw, would cause a whole lot of headache in terms of compatibility between Django 1.11± ? 

I just don't think I get your point. So maybe elaborate on it a little?

**Comment by Hopiu** [comment]
O.k. I'm unsure now, whether I got things right.
The problem that I am facing is, that I have more than one editor on a page, each of them is rendered through the template I posted in my first comment.
If I set special attrs on MarkdownxWidget they get rendered as an attribute on the editor textfield, but are not accessible by widget.html.

models.py:

    class SomeModel(models.Model):
        content = MarkdownxField()


forms.py:

    class SomeForm(ModelForm):
        class Meta:
            model = models.SomeModel
            widgets = {
                'content': widgets.MarkdownxWidget(attrs={'something': 'special'}),
            }

widget.html:

    
    <div>
        {{ markdownx_editor }}
    </div>

renders to:

    <div>
        <textarea class="markdownxwidget form-control markdownx-editor" cols="40" data-markdownx-upload-urls-path="/markdownx/upload/" data-markdownx-urls-path="/markdownx/markdownify/" something="special" id="id_content" name="content" rows="10" data-markdownx-editor-resizable="" required="" style="height: 218px;">Eos sunt molestias adipisci sit cum nobis. Animi quisquam nam nesciunt tenetur aut quas dolore porro. Quo magni architecto perferendis odio repellendus voluptas inventore.</textarea>
    </div>

But I am unable to add 'something=special' to the outer div. Or am I wrong?
That's why I added those other attributes to the 'attrs' dict.

How would you add something like the id on the outer div?

**Comment by xenatisch** [comment]
aaaah, I see now. You want to modify the outer `div` element, not the editor/preview. 

Have you tried altering the template locally? Here is the instruction on how to [customise the template](https://neutronx.github.io/django-markdownx/example.html#advanced) wihtin your project. 

Have a look and let me know if it helps.

**Comment by Hopiu** [comment]
> aaaah, I see now. You want to modify the outer div element, not the editor/preview.

Exactly. 

Yes, I tried altering the template according to the instructions on [customise the template](https://neutronx.github.io/django-markdownx/example.html#advanced). But then I'm not able to access the `attrs` dict from the widget template, as only the rendered `markdownx_editor` is passed to it.

**Comment by xenatisch** [comment]
Right. If you customise the template locally, you wouldn't need to use `attrs`. When rendering, you can simply pass your attributes directly. 

Note that this example assume you are using Django 1.11.

Say this is your custom template:

This would be saved under `templates/markdownx/widget.html
``` html
<div class="markdownx" {% for item in outer_editor_attrs %}{{ item.key }}{{ item.value }}{% endfor %}>
        {{ markdownx_editor }}
</div>

<div {% for item in outer_preview_attrs %}{{ item.key }}{{ item.value }}{% endfor %}>
    <div class="markdownx-preview"></div>
</div>
```

Then where you are intending to use it, say in your `index.html`, you would do this in your `my_app/views.py`:

``` python
from my_app.models import MyModel

class TestCreateView(CreateView):
    template_name = "index.html"
    model = MyModel
    success_url = '/'
    fields = [
        'markdownx_field1',
        'markdownx_field2',
        'textfield1',
        'textfield2'
    ]

    def render_to_response(self, context, **response_kwargs):
        results, template, contenxt, using, kwargs = super(TestCreateView, self).render_to_response()

        context.update({
            'outer_editor_attrs': [
                {'special_attr': 'value1'},
                {'another_attr': 'value2'}
            ],
            'outer_preview_attrs': [
                {'prev_special_attr': 'val1'},
                {'prev_another_attr': 'val2'}
            ]
        })

        return results, template, context, using, kwargs
```
This will ensure that these attributes are include the way you want them to. If you want each editor/preview set in your page to have different special attributes, then you're gonna have to inherit the widget and override the attributes manually. 

Make sure you don't include another `class` attribute. If you want to do that, you need to do so by passing them to the widgets or there will be 2 `class` attributes in your template and browsers don't like that (not to mention that XHTML wouldn't let it pass anyway). 

I am not quite sure how useful this is to other people since you are the first person asking for it (and specially because when I wanted to do something like this, I resorted to using JavaScript myself - see the image). I shall nonetheless consider adding a feature for adding attributes to the outer elements in our future minor release, provided that @adi- doesn't have any objections to it. 

screen shot 2017-04-26 at 11 36 22

**Pull request closed without merging**
