### PR TITLE
Fix missing attributes in widget rendering context

### LINKED ISSUE #99: Widget Customisation: Setting Class Attribute Takes No Effect
Given the following ModelForm:

```
class ModelForm(forms.ModelForm):

    class Meta:
        model = Model
        fields = (
            "title",
            "content"
        )
        widgets = {
            "content": MarkdownxWidget(attrs={'class': 'bla', 'style': 'resize:none; width: 100%;'}),
        }
```

Results in:
`<textarea class="markdownx-editor" style="resize: none; width: 100%; transition: opacity 1s ease 0s;" ...></textarea>`

Somehow https://github.com/neutronX/django-markdownx/blob/master/markdownx/widgets.py#L81 doesn't seem to work.

Tested with ``Django==1.11.3``,  ``django-markdownx==2.0.21`` and ``Python 3.5``.

_______

``widget2.html``:

```
<div class="markdownx row">
    <div class="col-md-6">
        {% include 'django/forms/widgets/textarea.html' %}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>
```

``settings.py``:
```
[...]
INSTALLED_APPS = [
    ...,
    'django.forms',
    'markdownx',
    ...
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

[...]
```

### PR DESCRIPTION
**Pull request by destos**
fixes #99

### CODE REVIEW

**Comment by adi-** [comment]
Already implemented

**Comment by destos** [comment]
@adi- Could you clarify where this is implemented? I'm not seeing a fix in the latest release. This change allows html attributes to be set on the widget html. Where before they are getting discarded. This is useful for styling the widget in custom layouts for the live preview feature.

**Comment by adi-** [comment]
Damn, @destos my fault. I would promise that I have already pull those fixes from other PRs. I am really sorry.

Could you update your PR with recent code from repo's master branch? Also, could you check this PR https://github.com/neutronX/django-markdownx/pull/118 into consideration? I can't verify it right now, but it seems to be a very close problem.

**Comment by adi-** [comment]
Ok, your fix is in repo now.

**Comment by adi-** [comment]
Please also check #118

**Comment by destos** [comment]
@adi- Thanks for merging it. I had originally looked at #118 but noticed it ignores the attributes that `render` may be attempting to add. In this PR I made sure it adds the regular widget attrs, and then have markdownx process them and add it's own. As I noticed `add_markdownx_attrs` checks for existing attrs in some cases before adding its own. Especially around CSS classes.

**Comment by adi-** [comment]
Great! I will push this fix to PyPi later today.

**Comment by adi-** [comment]
Pushed to v2.0.26

**Pull request merged**
