### PR TITLE
Add testing for Django 2.2a1

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by adi-** [comment]
Tim, could you ping me on Telegram? My username is @aaadeji

**Comment by timgraham** [comment]
I'm not on Telegram.

**Comment by adi-** [comment]
Ok, any other way to contact you?

**Comment by timgraham** [comment]
IRC is timograham. Email address is on my commits.

**Comment by adi-** [comment]
Already done.

**Pull request closed without merging**
