### PR TITLE
Handle csrf stored in sessions

### PR DESCRIPTION
**Pull request by Darkaird**
This allow to use CSRF_USE_SESSIONS = True which store crsf token in session instead of cookies.
It checks if csrf token found in cookies otherwise try to get csrf token in session.

### CODE REVIEW

**Comment by TheBuky** [comment]
Use full modification !
When `CSRF_USE_SESSIONS = True` in `settings.py` when can't use mardkownx => 403 error, with is modification the error is fixe.

**Comment by JeroenvO** [comment]
It would be nice to have this implemented :)

**Comment by TheBuky** [comment]
Yes for sure, this feature will be very useful when we change the method to handle the CSRF token.
In this MR, @Darkaird propose a simple way:
```
if we find the CSRF token:
   deal with it
else:
   search it in sessions
```

There is surely a way "more pretty" by giving the mode used by Django to handle the token from the `settings.py` but this is much more complex and this way can completely do the job.

The fact that **travis-ci** job crash is not to be considered because `no language set` for the job who fail. What is necessary to add this feature @adi- ?

**Comment by JeroenvO** [comment]
> There is surely a way "more pretty" by giving the mode used by Django to handle the token from the `settings.py` but this is much more complex and this way can completely do the job.

In that case django has to parse the .js file as template before serving it, thats not pretty either.

**Comment by JeroenvO** [comment]
Clearly a mistake indeed, i overlooked it in the diff. Can you correct this @TheBuky

**Comment by adi-** [comment]
Also, please update PR to latest code from github. There is already a fix for travis error.

**Comment by Darkaird** [comment]
My bad, what a shameful newbie mistake...
I just edit it.

**Comment by AjibsBaba** [comment]
> This allow to use CSRF_USE_SESSIONS = True which store crsf token in session instead of cookies.
> It checks if csrf token found in cookies otherwise try to get csrf token in session.

This was helpful

**Pull request merged**
