### PR TITLE
Fixed reloading the Markdown editor when it's already initialized

### PR DESCRIPTION
**Pull request by patchman-sebastiaan**
When a form is dynamically loaded with Javascript on the page where already a form exists with a markdown field, it will double initialize the markdown editor, resulting in several bugs like:

- Loading the preview field twice
- Uploading the images twice

This change sets a data-markdownx-init attribute. If it exists, the editor isn't initialized again for that field.

### CODE REVIEW

**Comment by xenatisch** [comment]
Hi,

Thanks for your contribution. 

I should probably elaborate more on this in the documentations, but your modifications cannot be used in the current format because they are implemented on the auto-generated `.js` file. 

## Explanation

Our JavaScript code is written in TypeScript ([see the docs](https://neutronx.github.io/django-markdownx/js/js.html#compatibility)) using ECMA 2016 in files [markdownx.ts](https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/markdownx.ts) and [utils.ts](https://github.com/neutronX/django-markdownx/blob/master/static-src/markdownx/js/utils.ts) under `./static-src/markdownx/`. These are then trans-compiled onto the ECMA 5 standard to produce `.js`/`.min.js` files. Any changes made directly to the auto-generated files will thus be lost in the next compilation. The trans-compilation process is a semi-automated process that is launched through the [developers' environment](https://neutronx.github.io/django-markdownx/contribution.html).

## Solution

There are two ways we can go about this:

- I can implement the changes myself and commit them to the repository.

- You can do it yourself in the `.ts` file, then either compile and commit them, or alternatively if you don't want to go through the hassle, commit them and I will do the compilation work myself. 

The advantage of the latter option is that the contribution will be registered in your own name.

**Comment by patchman-sebastiaan** [comment]
Because we had to override the Javascript file within our own project, I included that Javascript file in this library and made the PR. It was a quick fix, didn't look at the typescript. However, put it in the Typescript file now.

I will replace the logic to the suggested location and will make a new commit.

**Comment by xenatisch** [comment]
@patchman-sebastiaan thanks for the quick fix. Don't worry about the logic if you haven't done it already. I should have added it with my comment in the first place.

I'm gonna make some changes in docs, and add some more docstring to the code anyway. I'll then take care of the logic too.

**Comment by patchman-sebastiaan** [comment]
@xenatisch haven't changed the logic yet, saw you committed something as well. I'll leave the other changes up to you.

**Comment by xenatisch** [comment]
Alright then. Once again, thanks a lot for this.

**Pull request merged**
